server:
  address: 0.0.0.0
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb+srv://WhereWe:oM6OW8f9NGM3C15y@wherewe-users.gitmz.mongodb.net/WhereWe-users?retryWrites=true&w=majority&appName=WhereWe-users
